#!/bin/bash


[[ ! -d "$SCRIPTS" ]] && echo 'The variable SCRIPTS is not defined.' && exit 1
[[ ! -n "$@" ]] && echo "Usage: new-script <file>" && exit 1

for i in "$@"; do
    [[ -e "$i" ]] && \
    read -p "$i already exists. Do you want to edit it?" ans
    case $ans in
	y|yes|yup|Y|Yes|YES) touch "$i";;
    esac
done

printf "#!/bin/bash\n\n\n" >> "$i"
touch "$i"
chmod +x "$i"
exec vim +3 "$i"


